version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "melbourne-rent-crawler"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rsm2df40tt41"
s3_prefix = "melbourne-rent-crawler"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
